/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.orchsik.object._01_ticket;

public class App {
    public String getGreeting() {
        return "Hello ticket!!!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
